name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    env:
      DEF_LIB: ${{ matrix.library }}
      SUB_OS: ${{ matrix.config.sub_os }}

    name: ${{ join(matrix.config.*, '-') }}-${{ matrix.make }}-${{ matrix.library }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        make: [ meson ]
        library: [ shared ]
        config:
          - os: ubuntu-18.04
            sub_os: none
          - os: ubuntu-20.04
            sub_os: none
          - os: ubuntu-latest
            sub_os: centos:7
          - os: ubuntu-latest
            sub_os: centos:8
          - os: ubuntu-latest
            sub_os: fedora:30
          - os: ubuntu-latest
            sub_os: fedora:31
          - os: ubuntu-latest
            sub_os: fedora:32
          - os: ubuntu-latest
            sub_os: fedora:33

    steps:
    - name: Checkout XVIO sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout DPDK sources
      run: git clone -b 18.11 --depth=1 git://dpdk.org/dpdk-stable dpdk

    - name: Build
      if: matrix.config.sub_os == 'none'
      run: bash .github/.ci/linux-build.sh

    - name: Build in docker
      if: matrix.config.sub_os != 'none'
      run: |
           repo_name=${GITHUB_REPOSITORY#*/}
           docker pull $SUB_OS
           docker run --name builder \
              -v $GITHUB_WORKSPACE:/__w/${repo_name}/${repo_name} \
              -w /__w/${repo_name}/${repo_name} \
              -e SUB_OS=$SUB_OS -e DEF_LIB=$DEF_LIB \
              $SUB_OS bash .github/.ci/linux-build.sh
           docker rm builder

